dist: bionic
language: python
group: edge
python: 3.8
os: linux

matrix:
  fast_finish: true
  include:
    ### PyQt 5.7.1 (Python 3.5)
    - python: 3.5
      env: TESTENV=py35-pyqt57
      dist: xenial

    ### macOS Mojave (10.14)
    - os: osx
      env: TESTENV=py37-pyqt514 OSX=mojave
      osx_image: xcode11.3
      language: generic
      python: 3.7

    ### macOS High Sierra (10.13)
    - os: osx
      env: TESTENV=py37-pyqt514 OSX=highsierra
      osx_image: xcode10.1
      language: generic
      python: 3.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/qutebrowser/qutebrowser/.cache

install:
  - bash scripts/dev/ci/install.sh "$TESTENV"
  - ulimit -c unlimited

script:
  - bash scripts/dev/ci/run.sh "$TESTENV"

after_failure:
  - bash scripts/dev/ci/travis_backtrace.sh
